name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 19
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true