name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v5

      - name: Use Node 20
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Use cached Yarn cache
        uses: actions/cache@v4.2.4
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: yarnCache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarnCache-

      - name: Install dependencies
        run: yarn install --immutable
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true